modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="epic_emotes"
version="1.0.0"
displayName="Epic Emotes"
credits=""
displayURL=""
authors="M3tte"

[[dependencies.epic_emotes]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36.2.39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.epic_emotes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
[[dependencies.epic_emotes]]
    modId="epicfight"
    mandatory=true
    versionRange="[16.6.4,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.epic_emotes]]
    modId="replaymod"
    mandatory=false
versionRange="[2.5.1,)"
    ordering="AFTER"
    side="BOTH"





